name: "Compiles the baseDir"
description: "Compiles typescript code into javascript"
inputs:
  baseDir:
    description: "The baseDir to compile"
    required: true

runs:
  using: "composite"
  steps:
    - name: Compile app
      shell: bash
      run: make compile baseDir=${{ inputs.baseDir }}

    - name: Cache build folder
      uses: actions/cache@v3
      with:
        path: ${{ inputs.baseDir }}/build
        key: build-${{ github.sha }}-${{ inputs.baseDir }}
