name: "Deploy to compute engine"
description: "Replaces the running instance with the latest on GCE"
inputs:
  stage:
    description: "The stage for deployment (development|staging|production)"
    required: true

  baseDir:
    description: "The baseDir to deploy to"
    required: true

  tag:
    description: "The docker tag to deploy to the baseDir"
    required: true
    default: latest

  gcr-service-json:
    description: "The P12 credentials to login to GCR with"
    required: true

runs:
  using: "composite"
  steps:
    - name: Get the project id for this stage
      id: meta
      shell: bash
      run: |-
        echo project_id=$(make print.project_id stage=${{ inputs.stage }}) >> $GITHUB_OUTPUT
        echo tag=$(basename ${{ inputs.tag }}) >> $GITHUB_OUTPUT

    - id: auth
      uses: google-github-actions/auth@v1
      with:
        credentials_json: ${{ inputs.gcr-service-json }}

    - name: Set up Cloud SDK
      uses: google-github-actions/setup-gcloud@v1
      with:
        project_id: ${{ steps.meta.outputs.project_id }}

    - name: Deploy the container
      shell: bash
      run: make cloudrun.deploy baseDir=${{ inputs.baseDir }} tag=${{steps.meta.outputs.tag}} stage=${{ inputs.stage }}
