name: "A wrapper around the actions/checkout action"
description: "Authenticated the action and checks out recursively"
inputs:
  token:
    description: "The NPM token to be used for package installs"
    default: ${{ github.token }}

  submodules:
    description: "The NPM token to be used for package installs"
    default: false

  scope:
    description: "The scope to use for the token"
    default: "kadima-tech"

outputs:
  token:
    description: "The Github Access Token"
    value: ${{ steps.credentials.outputs.token }}

runs:
  using: "composite"
  steps:
    # - uses: kadima-tech/actions/github-authenticate@master
    #   id: credentials
    #   with:
    #     credentials_token: ${{ inputs.credentials_token }}

    # - uses: actions/checkout@v3
    #   with:
    #     submodules: recursive
    #     token: ${{ steps.credentials.outputs.token }}

    - uses: actions/checkout@v4
      with:
        submodules: ${{ inputs.submodules }}
        token: ${{ inputs.token }}

    - name: "Authenticate with private npm registry"
      shell: bash
      run: |
        npm config set @${{ inputs.scope }}:registry https://npm.pkg.github.com
        npm config set //npm.pkg.github.com/:_authToken ${{ inputs.token }}
