name: "Setup NPM Job"
description: "Sets up an authorized NPM job"
inputs:
  baseDir:
    required: true
    description: "The baseDir to setup"
  scope:
    required: false
    default: "kadima-tech"
    description: "NPM Scope to use"
  token:
    required: true
    description: "NPM Token to use"

runs:
  using: "composite"
  steps:
    - uses: actions/setup-node@v4
      with:
        node-version: 20
        cache-dependency-path: "${{inputs.baseDir}}/yarn.lock"

    - name: "Authenticate with private npm registry"
      shell: bash
      run: |
        npm config set @${{ inputs.scope }}:registry https://npm.pkg.github.com
        npm config set //npm.pkg.github.com/:_authToken ${{ inputs.token }}

    - name: Install npm modules
      shell: bash
      run: make install baseDir=${{inputs.baseDir}}
