name: "Deploy to artifact registry"
description: "Builds a docker image and pushes it to GCR"
inputs:
  token:
    description: "The npm token to use for the build"
    required: true

  baseDir:
    description: "The baseDir to compile"
    required: true

  gcr-service-json:
    description: "The P12 credentials to login to GCR with"
    required: true

  tag:
    description: "The tag name"
    required: false
    default: latest

  install:
    default: true
    required: false
    description: "Install dependencies"

  project:
    required: true
    description: "The project for which we're running this"

  dockerfile:
    required: false
    description: "The docker file to use"

  context:
    required: false
    description: "The docker context to use"
    default: "."

  artifact-repository-project:
    required: true
    description: "The artifactory project to which the images should be deployed"

runs:
  using: "composite"
  steps:
    - name: Install NPM dependencies
      if: ${{ inputs.install == true }}
      uses: ./.github/actions/node
      with:
        token: ${{ inputs.token }}
        baseDir: ${{ inputs.baseDir }}

    - name: Cache build folder
      uses: actions/cache@v3
      with:
        path: ${{ inputs.baseDir }}/build
        key: build-${{ github.sha }}-${{ inputs.baseDir }}

    - id: auth
      uses: google-github-actions/auth@v1
      with:
        credentials_json: ${{ inputs.gcr-service-json }}

    - uses: google-github-actions/setup-gcloud@v1
      with:
        project_id: ${{ inputs.artifact-repository-project }}

    # Configure Docker to use the gcloud command-line tool as a credential
    # helper for authentication
    - name: login to gcp Docker
      shell: bash
      run: |-
        gcloud --quiet auth configure-docker europe-west1-docker.pkg.dev

    - name: extract basename from tag
      shell: bash
      id: base
      run: echo "tag=$(basename ${{ inputs.tag }})" >> $GITHUB_OUTPUT

    - name: determine dockerfile to use
      shell: bash
      id: dockerfile
      run: |-
        if [ -z "${{inputs.dockerfile}}" ]
        then
          echo "dockerfile=${{inputs.baseDir}}/docker/Dockerfile" >> $GITHUB_OUTPUT
          echo "context=${{inputs.baseDir}} >> $GITHUB_OUTPUT"
        else
          echo "dockerfile=${{inputs.dockerfile}}" >> $GITHUB_OUTPUT
          echo "context=${{inputs.context}} >> $GITHUB_OUTPUT"
        fi

    - id: docker-push-tagged
      name: Tag Docker image and push to Google Artifact Registry
      uses: docker/build-push-action@v3
      with:
        context: ${{ steps.dockerfile.outputs.context }}
        # cache-from: type=gha
        # cache-to: type=gha,mode=max
        file: ${{ steps.dockerfile.outputs.dockerfile }}
        build-args: |
          AUTH_TOKEN=${{ inputs.token }}
          SRC_DIR=${{ inputs.baseDir }}
        push: true
        tags: |
          europe-west1-docker.pkg.dev/${{ inputs.artifact-repository-project }}/${{ inputs.project }}/${{ inputs.baseDir }}:${{ steps.base.outputs.tag  }}
