name: Docker Image Deploy
on:
  workflow_call:
    inputs:
      project:
        required: true
        type: string
      baseDir:
        required: true
        type: string
      stage:
        required: true
        type: string
      tag:
        required: true
        type: string
    secrets:
      token:
        required: true
      artifact_registry_upload_key:
        required: false
      cloudrun_uploader_service_account:
        required: true

jobs:
  install-and-deploy:
    runs-on: ubuntu-latest
    timeout-minutes: 30

    steps:
      - uses: kadima-tech/actions/checkout@v1
        with:
          submodules: recursive
          token: ${{ secrets.token }}
      
      - name: Publish docker container
        uses: kadima-tech/actions/docker-push@v1
        with:
          token: ${{ github.token }}
          gcr-service-json: ${{ secrets.artifact_registry_upload_key }}
          baseDir: ${{ inputs.baseDir }}
          project: ${{ inputs.project }}
          tag: ${{ inputs.tag }}

      - name: Deploy to Google
        uses: kadima-tech/actions/deploy-to-cloudrun@v1
        with:
          baseDir: ${{ inputs.baseDir }}
          gcr-service-json: ${{ secrets.cloudrun_uploader_service_account }}
          stage: ${{ inputs.stage }}
          tag: ${{ inputs.tag }}
